### ISSUE TITLE
 Bolt cannot optimize programs compiled with “-fuse-ld=gold” on aarch64

### ISSUE THREAD

**Issue by ijinma** [facebookincubator/BOLT#157] opened 2021-05-19 08:20 UTC
Hi, @maksfb  
 I have some programs compiled using the gold linker. However, I find that the programs compiled using the gold linker on aarch64 cannot be optimized by the tool bolt. Some errors are reported:
```
BOLT-INFO: Starting pass: print dyno-stats after optimizations
BOLT-INFO: program-wide dynostats after all optimizations before SCTC and FOP:

                 903 : executed forward branches
                   0 : taken forward branches
            16443331 : executed backward branches
            16442150 : taken backward branches
                   0 : executed unconditional branches
                1221 : all function calls
                   0 : indirect calls
                   0 : PLT calls
            98665973 : executed instructions
            32886565 : executed load instructions
                   0 : executed store instructions
                   0 : taken jump table branches
                   0 : taken unknown indirect branches
            16444234 : total branches
            16442150 : taken branches
                2084 : non-taken conditional branches
            16442150 : taken conditional branches
            16444234 : all conditional branches
                   0 : linker-inserted veneer calls

                1181 : executed forward branches (+30.8%)
                   0 : taken forward branches (=)
            16443053 : executed backward branches (-0.0%)
            16441928 : taken backward branches (-0.0%)
                 221 : executed unconditional branches (+22000.0%)
                1221 : all function calls (=)
                   0 : indirect calls (=)
                   0 : PLT calls (=)
           107803693 : executed instructions (+9.3%)
            32886565 : executed load instructions (=)
                   0 : executed store instructions (=)
                   0 : taken jump table branches (=)
                   0 : taken unknown indirect branches (=)
            16444455 : total branches (+0.0%)
            16442149 : taken branches (-0.0%)
                2306 : non-taken conditional branches (+10.7%)
            16441928 : taken conditional branches (-0.0%)
            16444234 : all conditional branches (=)
                   0 : linker-inserted veneer calls (=)

BOLT-INFO: Finished pass: print dyno-stats after optimizations
BOLT-INFO: Starting pass: simplify-conditional-tail-calls
BOLT-INFO: Finished pass: simplify-conditional-tail-calls
BOLT-INFO: Starting pass: peepholes
BOLT-INFO: Finished pass: peepholes
BOLT-INFO: Starting pass: aligner
llvm-bolt: /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp:207: unsigned int {anonymous}::AArch64MCCodeEmitter::getMachineOpValue(const llvm::MCInst&, const llvm::MCOperand&, llvm::SmallVectorImpl<llvm::MCFixup>&, const llvm::MCSubtargetInfo&) const: Assertion `MO.isImm() && "did not expect relocated expression"' failed.
 #0 0x0000000001bcdcd0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Support/Unix/Signals.inc:565:0
 #1 0x0000000001bcdda8 PrintStackTraceSignalHandler(void*) /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Support/Unix/Signals.inc:632:0
 #2 0x0000000001bcbfec llvm::sys::RunSignalHandlers() /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Support/Signals.cpp:76:0
 #3 0x0000000001bcd6ac SignalHandler(int) /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Support/Unix/Signals.inc:407:0
 #4 0x0000fffe345207c0 (linux-vdso.so.1+0x7c0)
 #5 0x0000fffe33f85870 raise (/lib64/libc.so.6+0x35870)
 #6 0x0000fffe33f86c1c abort (/lib64/libc.so.6+0x36c1c)
 #7 0x0000fffe33f7ed1c (/lib64/libc.so.6+0x2ed1c)
 #8 0x0000fffe33f7ed9c (/lib64/libc.so.6+0x2ed9c)
 #9 0x0000000000d3abc8 (anonymous namespace)::AArch64MCCodeEmitter::getMachineOpValue(llvm::MCInst const&, llvm::MCOperand const&, llvm::SmallVectorImpl<llvm::MCFixup>&, llvm::MCSubtargetInfo const&) const /home/majin/install/tools/llvm-bolt/BOLT/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp:207:0
#10 0x0000000000d4eb60 (anonymous namespace)::AArch64MCCodeEmitter::getBinaryCodeForInstr(llvm::MCInst const&, llvm::SmallVectorImpl<llvm::MCFixup>&, llvm::MCSubtargetInfo const&) const /home/majin/install/tools/llvm-bolt/build/lib/Target/AArch64/AArch64GenMCCodeEmitter.inc:16095:0

```
Is there any way to fix it? Or what can I do to support "-fuse-ld=gold?
thanks，
ijinma

**Comment by ijinma** [comment] 2021-05-24 09:19
Is there any possibility to comment on this？@maksfb  :)

**Comment by maksfb** [comment] 2021-05-24 18:11
Does it happen with every binary? Could you share a small binary to repro?

**Comment by ijinma** [comment] 2021-05-25 08:23
> Does it happen with every binary? Could you share a small binary to repro?

> Does it happen with every binary? 

yes,  at least all the programs I'm running, including speccpu2017、some small examples and benchmark tests. I have tested on several aarch64 machines and the results ware the same.

> Could you share a small binary to repro?

A common example: [https://github.com/ijinma/test_for_bolt](https://github.com/ijinma/test_for_bolt) , This is a bubble sort program compiled by gcc 9.3 with ```-fuse_ld=gold```.
If ```-fuse_ld=gold``` is not added at compile time, the bolt result is normal. Using ```gcc -Wl,-q -fuse_ld=gold test.c -o test```, the error is reported as follows, and the [detailed ](https://github.com/ijinma/test_for_bolt/blob/master/README.md)log is here. 
![bolt_error1](https://user-images.githubusercontent.com/57284757/119463536-70210400-bd74-11eb-9b6b-060be84ad625.png)

At the same time, If ```-O2``` optimization is used, such as ```gcc -Wl,-q -fuse_ld=gold -O2 test.c -o test```, the error is as follows:
![bolt_error2](https://user-images.githubusercontent.com/57284757/119463213-1fa9a680-bd74-11eb-8a47-81a8fed1ed9b.png)

It seems that some instructions are unrecognized or incorrectly recognized.

thanks @maksfb  :>
ijinma

**Comment by ijinma** [comment] 2021-05-26 07:36
Do you need anything else? Or what do I need to do? By the way, cross-compiled aarch64 programs on x86_64 (using the gold linker "-fuse-ld=god") also have some different bugs. :)

**Comment by aaupov** [comment] 2021-08-13 15:34
I've looked into the issue and it appears that with `-fuse-ld=gold` there are relocations that confuse BOLT:

objdump -dr, without `-fuse-ld=gold`:
```
0000000000000610 <main>:
 610:   5290d3e2        mov     w2, #0x869f                     // #34463
 614:   a9bd7bfd        stp     x29, x30, [sp, #-48]!
 618:   d284e203        mov     x3, #0x2710                     // #10000
 61c:   72a00022        movk    w2, #0x1, lsl #16
 620:   910003fd        mov     x29, sp
 624:   d503201f        nop
 628:   940000b0        bl      8e8 <foo_b>
                        628: R_AARCH64_CALL26   foo_b
 62c:   b9001bff        str     wzr, [sp, #24]
 630:   b9401be0        ldr     w0, [sp, #24]
 634:   6b02001f        cmp     w0, w2
 638:   5400010c        b.gt    658 <main+0x48>
 63c:   d503201f        nop
```

With `-fuse-ld=gold`:
```
00000000000005e0 <main>:
 5e0:   5290d3e2        mov     w2, #0x869f                     // #34463
 5e4:   a9bd7bfd        stp     x29, x30, [sp, #-48]!
 5e8:   d284e203        mov     x3, #0x2710                     // #10000
 5ec:   72a00022        movk    w2, #0x1, lsl #16
                        5ec: R_AARCH64_ADR_PREL_PG_HI21 __init_array_end
 5f0:   910003fd        mov     x29, sp
                        5f0: R_AARCH64_ADD_ABS_LO12_NC  __init_array_end
 5f4:   d503201f        nop
 5f8:   940000b0        bl      8b8 <foo_b>
                        5f8: R_AARCH64_CALL26   foo_b
                        5f8: R_AARCH64_ADR_PREL_PG_HI21 __init_array_start
 5fc:   b9001bff        str     wzr, [sp, #24]
                        5fc: R_AARCH64_ADD_ABS_LO12_NC  __init_array_start
```

I'm not an ARM expert but these `__init_array_end` relocations appears erroneous:
> 5f0:   910003fd        mov     x29, sp
                        5f0: R_AARCH64_ADD_ABS_LO12_NC  __init_array_end

So my advice would be to avoid `-fuse-ld=gold`. If you could raise that issue with gold developers, it would be of immense help for us to decide what to do with these relocations if they are valid.

**Comment by aaupov** [comment] 2021-08-16 03:43
Checked AArch64 ELF ABI to confirm that ADR/ADD relocations are not applicable to movk/mov instructions:
https://github.com/ARM-software/abi-aa/blob/2bcab1e3b22d55170c563c3c7940134089176746/aaelf64/aaelf64.rst#id53

**Comment by ijinma** [comment] 2021-08-16 07:49
> I've looked into the issue and it appears that with `-fuse-ld=gold` there are relocations that confuse BOLT:
> 
> objdump -dr, without `-fuse-ld=gold`:
> 
> ```
> 0000000000000610 <main>:
>  610:   5290d3e2        mov     w2, #0x869f                     // #34463
>  614:   a9bd7bfd        stp     x29, x30, [sp, #-48]!
>  618:   d284e203        mov     x3, #0x2710                     // #10000
>  61c:   72a00022        movk    w2, #0x1, lsl #16
>  620:   910003fd        mov     x29, sp
>  624:   d503201f        nop
>  628:   940000b0        bl      8e8 <foo_b>
>                         628: R_AARCH64_CALL26   foo_b
>  62c:   b9001bff        str     wzr, [sp, #24]
>  630:   b9401be0        ldr     w0, [sp, #24]
>  634:   6b02001f        cmp     w0, w2
>  638:   5400010c        b.gt    658 <main+0x48>
>  63c:   d503201f        nop
> ```
> 
> With `-fuse-ld=gold`:
> 
> ```
> 00000000000005e0 <main>:
>  5e0:   5290d3e2        mov     w2, #0x869f                     // #34463
>  5e4:   a9bd7bfd        stp     x29, x30, [sp, #-48]!
>  5e8:   d284e203        mov     x3, #0x2710                     // #10000
>  5ec:   72a00022        movk    w2, #0x1, lsl #16
>                         5ec: R_AARCH64_ADR_PREL_PG_HI21 __init_array_end
>  5f0:   910003fd        mov     x29, sp
>                         5f0: R_AARCH64_ADD_ABS_LO12_NC  __init_array_end
>  5f4:   d503201f        nop
>  5f8:   940000b0        bl      8b8 <foo_b>
>                         5f8: R_AARCH64_CALL26   foo_b
>                         5f8: R_AARCH64_ADR_PREL_PG_HI21 __init_array_start
>  5fc:   b9001bff        str     wzr, [sp, #24]
>                         5fc: R_AARCH64_ADD_ABS_LO12_NC  __init_array_start
> ```
> 
> I'm not an ARM expert but these `__init_array_*` relocations appear erroneous:
> 
> ```
>  5ec:   72a00022        movk    w2, #0x1, lsl #16
>                         5ec: R_AARCH64_ADR_PREL_PG_HI21 __init_array_end
>  5f0:   910003fd        mov     x29, sp
>                         5f0: R_AARCH64_ADD_ABS_LO12_NC  __init_array_end
> ```
> 
> So my advice would be to avoid using `-fuse-ld=gold`. If you could raise that issue with gold developers, it would be of immense help for us to decide what to do with these relocations if they are valid.

Hi, we have also found this problem, As yota @yota9-huawei  says: "The ADR_PREL relocation is used for ADRP instruction, but it is used for b here, it is some kind of mess.." .
![image](https://user-images.githubusercontent.com/57284757/129528155-a4c94d86-e93e-4d0e-8931-e39be5c02e53.png)
And yota seems to be fixing this type of problem :) . By the way, I'm a beginner in linker relocations , so can only expect progress on yota's fix.

**Comment by aaupov** [comment] 2021-08-16 08:09
I've filed a bug on gold's bugzilla: https://sourceware.org/bugzilla/show_bug.cgi?id=28234.
As far as I can see, the issue is not with BOLT, so I'm closing this issue.

**Closed by aaupov** 2021-08-16 08:09 UTC
Labels: bug
