### ISSUE TITLE
Disassemble issue with gcc builit binary

### ISSUE THREAD

**Issue by raghesh** [facebookincubator/BOLT#117] opened 2021-02-16 08:41 UTC
Getting the following error while using llvm-bolt with gcc built binary.

"BOLT-ERROR: unable to disassemble instruction in PLT section .plt.got at offset 0x8"

**Tested program - test.c**

int main() {
}

**Commands used**

gcc -O0  -g -Wl,-emit-relocs test.c -o test.gcc.out
llvm-bolt -lite=0 -print-cfg ./test.gcc.out -o /dev/null

**Objdump output**

The output of objdump -d test.gcc.out -j .plt.got

test.gcc.out:     file format elf64-x86-64

Disassembly of section .plt.got:

0000000000001030 <__cxa_finalize@plt>:
    1030:       f3 0f 1e fa             endbr64 
    1034:       f2 ff 25 bd 2f 00 00    bnd jmpq *0x2fbd(%rip)        # 3ff8 <__cxa_finalize@GLIBC_2.2.5>
    103b:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

Looks like the bnd prefix is not recognized. This was tested on an AMD machine.

I tested on a different (intel) machine, the issue is not there. The output of objdump there was as follows.

test.gcc.out:     file format elf64-x86-64

Disassembly of section .plt.got:

00000000000004e0 <__cxa_finalize@plt>:
 4e0:   ff 25 12 0b 20 00       jmpq   *0x200b12(%rip)        # 200ff8 <__cxa_finalize@GLIBC_2.2.5>
 4e6:   66 90                   xchg   %ax,%ax

The bnd prefix is not present here.

**Comment by aagontuk** [comment] 2021-02-16 13:26
Which gcc version are you using?

>NOTE: BOLT is currently incompatible with the -freorder-blocks-and-partition compiler option. Since GCC8 enables this option by default, you have to explicitly disable it by adding -fno-reorder-blocks-and-partition flag if you are compiling with GCC8.

Did you try compiling with `-fno-reorder-blocks-and-partition`?

**Comment by raghesh** [comment] 2021-02-17 01:03
> Which gcc version are you using?
> 

I am using gcc-10

> > NOTE: BOLT is currently incompatible with the -freorder-blocks-and-partition compiler option. Since GCC8 enables this option by default, you have to explicitly disable it by adding -fno-reorder-blocks-and-partition flag if you are compiling with GCC8.
> 
> Did you try compiling with `-fno-reorder-blocks-and-partition`?

With -fno-reorder-blocks-and-partition the issue persists.

$ gcc-10 -fno-reorder-blocks-and-partition -Wl,-emit-relocs test.c -o test.gcc.out
$ llvm-bolt -lite=0 -print-cfg test.gcc.out  -o /dev/null
BOLT-INFO: shared object or position-independent executable detected
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: f137ed238db11440f03083b1c88b7ffc0f4af65e
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x200000, offset 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling -align-macro-fusion=all since no profile was specified
BOLT-ERROR: unable to disassemble instruction in PLT section .plt.got at offset 0x8

**Comment by maksfb** [comment] 2021-07-08 18:30
The issue should be fixed in the "rebased" branch of BOLT repo.

**Comment by vleonen** [comment] 2021-07-09 07:54
@maksfb I still can reproduce the issue with new tests for instrumentation support introduced in MR#184 commit 439ffb597c774556b505809032b01eb477be94b1
There is a workaround commit on top of that MR, but it breaks tests for gcc versions older than gcc-8 due to usage of the newly introduced option -fcf-protection : b9ce0d79abe7daff171e7c31c18dcec3bf058c82

My environment:
Ubuntu 20.04.2 LTS 
$ /usr/bin/cc --version
cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

The issue log:
: 'RUN: at line 24';   /usr/bin/cc  -no-pie /home/vleonenko/bolt/llvm-bolt/bolt/test/X86/instrumentation-pie.c -o /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.exe -Wl,-q -pie -fpie
: 'RUN: at line 26';   /home/vleonenko/bolt/llvm-bolt/build/bin/llvm-bolt /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.exe -instrument -instrumentation-file=/home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.fdata    -o /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.instrumented
: 'RUN: at line 30';   /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.instrumented 1 2 3 | /home/vleonenko/bolt/llvm-bolt/build/bin/FileCheck /home/vleonenko/bolt/llvm-bolt/bolt/test/X86/instrumentation-pie.c -check-prefix=CHECK-OUTPUT
: 'RUN: at line 33';    /home/vleonenko/bolt/llvm-bolt/build/bin/llvm-bolt /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.exe -o /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.bolted -data /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.fdata     -reorder-blocks=cache+ -reorder-functions=hfsort+
: 'RUN: at line 36';   /home/vleonenko/bolt/llvm-bolt/build/tools/bolt/test/X86/Output/instrumentation-pie.c.tmp.bolted 1 2 3  | /home/vleonenko/bolt/llvm-bolt/build/bin/FileCheck /home/vleonenko/bolt/llvm-bolt/bolt/test/X86/instrumentation-pie.c -check-prefix=CHECK-OUTPUT
--
Exit Code: 1

Command Output (stdout):
--
BOLT-INFO: shared object or position-independent executable detected
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: 439ffb597c774556b505809032b01eb477be94b1
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x200000, offset 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: enabling -align-macro-fusion=all since no profile was specified
BOLT-INFO: enabling lite mode

--
Command Output (stderr):
--
BOLT-ERROR: unable to disassemble instruction in PLT section .plt.got at offset 0x8

--

**Comment by maksfb** [comment] 2021-07-09 17:22
Is there `bnd jmp...` instruction in your `.plt.got` at 0x8?
403b668 includes a test case `plt-sec.test`. Does it pass for you? It should have the same `bnd` prefix.

**Comment by vleonen** [comment] 2021-07-09 21:42
@maksfb Yes, there is `bnd jmpq` instruction. But I found that each PLT entry in my case is 16-byte size, while Bolt assumes that .plt.got entries are 8-byte size.
```
0000000000001040 <__cxa_finalize@plt>:
    1040:       f3 0f 1e fa             endbr64
    1044:       f2 ff 25 ad 2f 00 00    bnd jmpq *0x2fad(%rip)        # 3ff8 <__cxa_finalize@GLIBC_2.2.5>
    104b:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
```
Also, I found that test introduced in 403b668  doesn't produce .plt.got section (only .plt & .plt.sec), so .plt.got case is not checked.
Based on this - I made a simple patch that changes .plt.got entry size to match the size in binaries in my environment (gcc-9, Ubuntu-20.04):
```
diff --git a/bolt/src/RewriteInstance.h b/bolt/src/RewriteInstance.h
index 0ce8a81c8ad4..18dcee6777d5 100644
--- a/bolt/src/RewriteInstance.h
+++ b/bolt/src/RewriteInstance.h
@@ -454,7 +454,7 @@ private:
   /// Different types of X86-64 PLT sections.
   const PLTSectionInfo X86_64_PLTSections[4] = {
       { ".plt", 16 },
-      { ".plt.got", 8 },
+      { ".plt.got", 16 },
       { ".plt.sec", 16 },
       { nullptr, 0 }
   };
```
After that, my tests (439ffb5) passed.

**Comment by maksfb** [comment] 2021-07-09 21:54
Thanks for the info. Will have to find a better way to parse PLT sections. We have test cases where `.plt.got` entries are 8-bytes long and this patch will break them.

**Comment by vleonen** [comment] 2021-07-16 15:49
Hello @maksfb 
I'm wondering if Bolt team has a plan to introduce better support for PLT entries size detection in near future?
Can you share or point at existing tests that use 8-bytes long .plt.got entries?

**Comment by maksfb** [comment] 2021-07-16 15:52
Hi Vasily, thanks for checking. Yes, I’ll post the fix and the test case.

**Comment by maksfb** [comment] 2022-04-22 18:39
Was fixed in "[BOLT] Support PLT sections with variable entry sizes".

**Closed by maksfb** 2022-04-22 18:39 UTC
